#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("DopplerMobile.Android.UnitTest.Resource", IsApplication=true)]

namespace DopplerMobile.Android.UnitTest
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxBind = global::DopplerMobile.Android.UnitTest.Resource.Attribute.MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxDropDownItemTemplate = global::DopplerMobile.Android.UnitTest.Resource.Attribute.MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxGroupItemTemplate = global::DopplerMobile.Android.UnitTest.Resource.Attribute.MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxItemTemplate = global::DopplerMobile.Android.UnitTest.Resource.Attribute.MvxItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxLang = global::DopplerMobile.Android.UnitTest.Resource.Attribute.MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxSource = global::DopplerMobile.Android.UnitTest.Resource.Attribute.MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Attribute.MvxTemplate = global::DopplerMobile.Android.UnitTest.Resource.Attribute.MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Id.MvvmCrossTagId = global::DopplerMobile.Android.UnitTest.Resource.Id.MvvmCrossTagId;
			global::MvvmCross.Binding.Droid.Resource.Id.MvxBindingTagUnique = global::DopplerMobile.Android.UnitTest.Resource.Id.MvxBindingTagUnique;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxBinding;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxBind = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxBinding_MvxBind;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxBinding_MvxLang = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxBinding_MvxLang;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxControl;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxControl_MvxTemplate = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxControl_MvxTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxExpandableListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxExpandableListView_MvxGroupItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxImageView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxImageView_MvxSource = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxImageView_MvxSource;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxListView;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxDropDownItemTemplate = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxListView_MvxDropDownItemTemplate;
			global::MvvmCross.Binding.Droid.Resource.Styleable.MvxListView_MvxItemTemplate = global::DopplerMobile.Android.UnitTest.Resource.Styleable.MvxListView_MvxItemTemplate;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionHostName = global::DopplerMobile.Android.UnitTest.Resource.Id.OptionHostName;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionPort = global::DopplerMobile.Android.UnitTest.Resource.Id.OptionPort;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionRemoteServer = global::DopplerMobile.Android.UnitTest.Resource.Id.OptionRemoteServer;
			global::Xamarin.Android.NUnitLite.Resource.Id.OptionsButton = global::DopplerMobile.Android.UnitTest.Resource.Id.OptionsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultFullName = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultFullName;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultMessage = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultResultState = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultResultState;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultRunSingleMethodTest = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultRunSingleMethodTest;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultStackTrace = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultStackTrace;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsFailed = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultsFailed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsId = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultsId;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsIgnored = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultsIgnored;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsInconclusive = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultsInconclusive;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsMessage = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultsMessage;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsPassed = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultsPassed;
			global::Xamarin.Android.NUnitLite.Resource.Id.ResultsResult = global::DopplerMobile.Android.UnitTest.Resource.Id.ResultsResult;
			global::Xamarin.Android.NUnitLite.Resource.Id.RunTestsButton = global::DopplerMobile.Android.UnitTest.Resource.Id.RunTestsButton;
			global::Xamarin.Android.NUnitLite.Resource.Id.TestSuiteListView = global::DopplerMobile.Android.UnitTest.Resource.Id.TestSuiteListView;
			global::Xamarin.Android.NUnitLite.Resource.Layout.options = global::DopplerMobile.Android.UnitTest.Resource.Layout.options;
			global::Xamarin.Android.NUnitLite.Resource.Layout.results = global::DopplerMobile.Android.UnitTest.Resource.Layout.results;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_result = global::DopplerMobile.Android.UnitTest.Resource.Layout.test_result;
			global::Xamarin.Android.NUnitLite.Resource.Layout.test_suite = global::DopplerMobile.Android.UnitTest.Resource.Layout.test_suite;
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010000
			public const int MvxBind = 2130771968;
			
			// aapt resource value: 0x7f010004
			public const int MvxDropDownItemTemplate = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int MvxGroupItemTemplate = 2130771973;
			
			// aapt resource value: 0x7f010003
			public const int MvxItemTemplate = 2130771971;
			
			// aapt resource value: 0x7f010001
			public const int MvxLang = 2130771969;
			
			// aapt resource value: 0x7f010006
			public const int MvxSource = 2130771974;
			
			// aapt resource value: 0x7f010002
			public const int MvxTemplate = 2130771970;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int Icon = 2130837504;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f040000
			public const int MvvmCrossTagId = 2130968576;
			
			// aapt resource value: 0x7f040001
			public const int MvxBindingTagUnique = 2130968577;
			
			// aapt resource value: 0x7f040003
			public const int OptionHostName = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int OptionPort = 2130968580;
			
			// aapt resource value: 0x7f040002
			public const int OptionRemoteServer = 2130968578;
			
			// aapt resource value: 0x7f040012
			public const int OptionsButton = 2130968594;
			
			// aapt resource value: 0x7f04000d
			public const int ResultFullName = 2130968589;
			
			// aapt resource value: 0x7f04000f
			public const int ResultMessage = 2130968591;
			
			// aapt resource value: 0x7f04000e
			public const int ResultResultState = 2130968590;
			
			// aapt resource value: 0x7f04000c
			public const int ResultRunSingleMethodTest = 2130968588;
			
			// aapt resource value: 0x7f040010
			public const int ResultStackTrace = 2130968592;
			
			// aapt resource value: 0x7f040008
			public const int ResultsFailed = 2130968584;
			
			// aapt resource value: 0x7f040005
			public const int ResultsId = 2130968581;
			
			// aapt resource value: 0x7f040009
			public const int ResultsIgnored = 2130968585;
			
			// aapt resource value: 0x7f04000a
			public const int ResultsInconclusive = 2130968586;
			
			// aapt resource value: 0x7f04000b
			public const int ResultsMessage = 2130968587;
			
			// aapt resource value: 0x7f040007
			public const int ResultsPassed = 2130968583;
			
			// aapt resource value: 0x7f040006
			public const int ResultsResult = 2130968582;
			
			// aapt resource value: 0x7f040011
			public const int RunTestsButton = 2130968593;
			
			// aapt resource value: 0x7f040013
			public const int TestSuiteListView = 2130968595;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int options = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int results = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int test_result = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int test_suite = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] MvxBinding = new int[] {
					2130771968,
					2130771969};
			
			// aapt resource value: 0
			public const int MvxBinding_MvxBind = 0;
			
			// aapt resource value: 1
			public const int MvxBinding_MvxLang = 1;
			
			public static int[] MvxControl = new int[] {
					2130771970};
			
			// aapt resource value: 0
			public const int MvxControl_MvxTemplate = 0;
			
			public static int[] MvxExpandableListView = new int[] {
					2130771973};
			
			// aapt resource value: 0
			public const int MvxExpandableListView_MvxGroupItemTemplate = 0;
			
			public static int[] MvxImageView = new int[] {
					2130771974};
			
			// aapt resource value: 0
			public const int MvxImageView_MvxSource = 0;
			
			public static int[] MvxListView = new int[] {
					2130771971,
					2130771972};
			
			// aapt resource value: 1
			public const int MvxListView_MvxDropDownItemTemplate = 1;
			
			// aapt resource value: 0
			public const int MvxListView_MvxItemTemplate = 0;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
