//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DopplerMobile.Resources {
    using System;
    using System.Reflection;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("DopplerMobile.Resources.Strings", typeof(Strings).GetTypeInfo().Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DopplerMobile.
        /// </summary>
        public static string ApplicationNameText {
            get {
                return ResourceManager.GetString("ApplicationNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hola Doppler Mobile.
        /// </summary>
        public static string HelloText {
            get {
                return ResourceManager.GetString("HelloText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to INICIAR SESIÓN.
        /// </summary>
        public static string LoginButtonText {
            get {
                return ResourceManager.GetString("LoginButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ¿OLVIDASTE TU CONTRASEÑA?.
        /// </summary>
        public static string LoginForgotPasswordText {
            get {
                return ResourceManager.GetString("LoginForgotPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to USUARIO.
        /// </summary>
        public static string LoginNameText {
            get {
                return ResourceManager.GetString("LoginNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CONTRASEÑA.
        /// </summary>
        public static string LoginPasswordText {
            get {
                return ResourceManager.GetString("LoginPasswordText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MvvmCross.
        /// </summary>
        public static string MvvmCrossText {
            get {
                return ResourceManager.GetString("MvvmCrossText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SIGUIENTE.
        /// </summary>
        public static string OnboardingButtonNextText {
            get {
                return ResourceManager.GetString("OnboardingButtonNextText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SALTAR.
        /// </summary>
        public static string OnboardingButtonSkipText {
            get {
                return ResourceManager.GetString("OnboardingButtonSkipText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Observa en tiempo real el éxito de tus campañas.
        /// </summary>
        public static string OnboardingTitlePageOneText {
            get {
                return ResourceManager.GetString("OnboardingTitlePageOneText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título Página Tres.
        /// </summary>
        public static string OnboardingTitlePageThreeText {
            get {
                return ResourceManager.GetString("OnboardingTitlePageThreeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Título Página Dos.
        /// </summary>
        public static string OnboardingTitlePageTwoText {
            get {
                return ResourceManager.GetString("OnboardingTitlePageTwoText", resourceCulture);
            }
        }
    }
}
