# More documentation about how to customize your build
# can be found here:
# https://docs.fastlane.tools
fastlane_version "1.109.0"

# This value helps us track success metrics for Fastfiles
# we automatically generate. Feel free to remove this line
# once you get things running smoothly!
generated_fastfile_id "ce2b279d-827e-4ef8-a85e-1a017d69fbb7"

default_platform :ios

# Fastfile actions accept additional configuration, but
# don't worry, fastlane will prompt you for required
# info which you can add here later
lane :beta do
  # build your iOS app
  gym(
    # scheme: "YourScheme",
    export_method: "ad-hoc"
  )

  # upload to Beta by Crashlytics
  crashlytics(
    # keys for organization: MakingSense
    api_token: "264be32f6a20170b5b6fcc25016e0100ace21d64",
    build_secret: "dfcbd7c046f6fcbbf80866150ab1c848e1a91ad573b64949b1898daeb1369c15"
  )
end
