source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "10.0"
use_frameworks!

target 'DopplerMobile' do
    pod 'GTProgressBar', '0.1.2'
    pod 'PagingMenuController'
    pod 'Alamofire', '4.4'
    pod 'SwiftyJSON', '3.1.4'
    pod 'SwiftyUserDefaults', '~> 3.0.0'
    pod 'Typhoon'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TextFieldEffects'
    pod 'DLRadioButton', '~> 1.4'
    pod 'Bond', '6.2.4'
    pod 'Charts', '3.0.2'
    pod 'IHKeyboardAvoiding', '3.7'
    pod "KRProgressHUD", '2.2.2'
    pod 'SwiftyOnboard', '1.3.3'
    pod 'Kingfisher', '3.9.1'
end

target 'DopplerMobileTests' do
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
