source 'https://github.com/CocoaPods/Specs.git'
platform :ios, "9.2"
use_frameworks!

target 'DopplerMobile' do
    pod 'PagingMenuController'
    pod 'Alamofire', '~> 4.0'
    pod 'SwiftyJSON', git: 'https://github.com/BaiduHiDeviOS/SwiftyJSON.git', branch: 'swift3'
    pod 'SwiftyUserDefaults', '~> 3.0.0'
    pod 'Typhoon'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'TextFieldEffects'
    pod 'DLRadioButton', '~> 1.4'
end

target 'DopplerMobileTests' do
    
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end




